when@dev:
    _errors:
        resource: '@FrameworkBundle/Resources/config/routing/errors.xml'
        prefix: /_error

# session:
#     handler_id: session.handler.native_file
#     save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
#         cookie_lifetime: 30